### ISSUE TITLE
crashes on 1.19 fabric

### ISSUE THREAD

**Issue by ImUrX** [itsmeowCommissions/SnailMail#7]
[logs](https://paste.ee/p/tUXXL)
sorry for not writing the template out, the logs mention everything ;-;

**Comment by ImUrX** [comment]
after checking its Inventory Sorting triggering SnailBoxMenu.stillValid() in the client side

**Comment by TofuToons** [comment]
Can confirm that this incompatibility with Inventory Sorting exists on the 1.18.2 fabric version as well

**Comment by itsmeow** [comment]
Hi, it seems the log expired.
