### ISSUE TITLE
[Fabric] [1.19.2] Crash after opening Members Menu / Opening Envelope

### ISSUE THREAD

**Issue by pewblaze** [itsmeowCommissions/SnailMail#8]
## Describe what you were doing before the crash
Trying to open an Envelope.

[eg. Loading game, creating world, spawning a certain mob, hurting a mob, walking around]

## To Reproduce

Steps to reproduce the behavior (if possible):
1. Spawn on the Server
2. Click on the Snailmail Box
3. Place an Envelope & try to open it or click on the Member Button
4. Hangs up & crashes

## Crash Log (REQUIRED)

https://gist.github.com/pewblaze/343d7fb526ed2b163d83ffc958a92988

## Versions
- Minecraft Version: 1.19.2
- Architectury API Version: architectury-6.2.43-fabric
- Platform (Forge/Fabric): Fabric
- Fabric Loader Version: 0.14.9
- Fabric API Version: fabric-api-0.60.0+1.19.2
- Mod Version: snailmail-1.19-1.1.0-fabric

## Additional context
We are playing on a server, i think singleplayer worked fine.

**Comment by BigPhobos** [comment]
Same issue on Forge
Forge: 1.19.2-43.1.58
Mod Version: snailmail-1.19-1.1.0-forge.jar
API: architectury-6.3.56-forge.jar

**Comment by itsmeow** [comment]
Fixed in 1.19.2 release
