### ISSUE TITLE
Members Menu Blank Screen Bug

### ISSUE THREAD

**Issue by mikewayno** [itsmeowCommissions/SnailMail#9]
## Describe the bug

When using the snail box the menu for member is completely gray

## To Reproduce
Use snail box, either attempt to send mail or access member a big gray box with no info shows up
** Note if you know where to click it will work. so mod is functioning but basically unusable unless you know where to click

## Log output/error (if present)

I have a screenshot but no errors 

https://imgur.com/cBmQzaZ

## Expected behavior

I expected to see the menu in full like in the screenshots or videos i have seen of this mod working

## Versions
 - Minecraft Version: 1.9.2
 - Architectury API Version:[v6.2.46]

 - Forge Version: 1.9.2 - 43.1.39

## Additional context

mods installed server are 
BiomesOPlenty
jei
TerraBlender
inventorysorter
snailmail
dynmap
architectury
worldedit
worldguard
gravestone
OptiFine

**Comment by itsmeow** [comment]
I expect this could be related to GUI scale / resolution issues

**Comment by itsmeow** [comment]
Fixed in 1.19.2 release
